"""Add publisher field to news table

Revision ID: 6d7914add71c
Revises: fdc628bd4d06
Create Date: 2025-12-01 08:25:10.535724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d7914add71c'
down_revision: Union[str, None] = 'fdc628bd4d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add publisher column to news table
    op.add_column('news', sa.Column('publisher', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_news_publisher'), 'news', ['publisher'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only remove publisher column from news table
    op.drop_index(op.f('ix_news_publisher'), table_name='news')
    op.drop_column('news', 'publisher')
    # ### end Alembic commands ###
