"""Add department field to news table

Revision ID: fdc628bd4d06
Revises: d3844a6b4068
Create Date: 2025-12-01 03:56:30.426731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdc628bd4d06'
down_revision: Union[str, None] = 'd3844a6b4068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add department column to news table
    op.add_column('news', sa.Column('department', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_news_department'), 'news', ['department'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only remove department column from news table
    op.drop_index(op.f('ix_news_department'), table_name='news')
    op.drop_column('news', 'department')
    # ### end Alembic commands ###
